//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id { get; set; }
        public string name { get; set; }
        public int product_id { get; set; }
        public int user_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<decimal> sum { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
    }
}
